import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent, type RefObject } from 'react';
import { Link, Route, Switch, useLocation } from 'wouter';
import {
  ArrowDown, ArrowUp, Braces, Check, CircleHelp, Copy,
  Download, ExternalLink, FileJson, Globe2, GripVertical, Layers3,
  LockKeyhole, Plus, RotateCcw, Settings2, ShieldCheck, SlidersHorizontal,
  Trash2, Upload, X, Zap,
} from 'lucide-react';
import { createId, RESOURCE_TYPES, type AppStorage, type FilterCondition, type HeaderRule, type Profile, type ResourceType } from '@/lib/model';
import { loadConfig, saveConfig, subscribeToConfig } from '@/lib/storage';
import { applyImportedConfig, parseConfigurationImport } from '@/lib/import-utils';
import { matchesUrlPattern } from '@/lib/dnr';

type ModalState = { kind: 'header'; item?: HeaderRule } | { kind: 'filter'; item?: FilterCondition } | { kind: 'profile'; item?: Profile } | null;
const COLOR_TAGS = ['teal', 'violet', 'amber', 'rose', 'blue', 'slate'];
const COLOR_MAP: Record<string,string> = { teal:'#39876f', violet:'#8270a9', amber:'#c28b45', rose:'#c46f74', blue:'#6389ad', slate:'#73808d' };
const TYPE_LABELS: Record<string,string> = { main_frame:'Main frame', sub_frame:'Sub frame', stylesheet:'Stylesheet', script:'Script', image:'Image', font:'Font', object:'Object', xmlhttprequest:'XHR / fetch', ping:'Ping', csp_report:'CSP report', media:'Media', websocket:'WebSocket', other:'Other' };

function App() {
  const [config, setConfig] = useState<AppStorage | null>(null);
  const [loadError, setLoadError] = useState('');
  const [saving, setSaving] = useState(false);
  const [modal, setModal] = useState<ModalState>(null);
  const [toast, setToast] = useState('');
  const [location, setLocation] = useLocation();
  const [selectedProfileId, setSelectedProfileId] = useState('');
  const [popupTab, setPopupTab] = useState<'request'|'response'|'filters'>('request');
  const [bulkSelected, setBulkSelected] = useState<string[]>([]);
  const [testUrl, setTestUrl] = useState('');
  const [testProfileId, setTestProfileId] = useState('');
  const [restoreMode, setRestoreMode] = useState<'merge'|'replace'>('merge');
  const [importText, setImportText] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  const activeProfile = useMemo(() => config?.profiles.find(p => p.id === selectedProfileId) ?? config?.profiles.find(p => config.activeProfileIds.includes(p.id)) ?? config?.profiles[0], [config, selectedProfileId]);
  const isOptions = location === '/options' || window.location.pathname.endsWith('/options.html');

  useEffect(() => {
    let alive = true;
    loadConfig().then(value => {
      if (alive) {
        setConfig(value);
        setSelectedProfileId(value.activeProfileIds[0] ?? value.profiles[0]?.id ?? '');
      }
    }).catch(err => { if (alive) setLoadError(err instanceof Error ? err.message : 'Could not load local configuration.'); });
    const unsubscribe = subscribeToConfig(value => {
      setConfig(value);
      setSelectedProfileId(current => value.profiles.some(profile => profile.id === current) ? current : value.activeProfileIds[0] ?? value.profiles[0]?.id ?? '');
    });
    return () => { alive = false; unsubscribe(); };
  }, []);
  useEffect(() => {
    if (!config) return;
    document.documentElement.classList.toggle('dark', config.settings.theme === 'dark' || (config.settings.theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches));
  }, [config?.settings.theme]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 2600); return () => clearTimeout(timer); }, [toast]);

  const mutate = useCallback((fn: (current: AppStorage) => AppStorage, message?: string) => {
    if (!config) return;
    const next = fn(config);
    setConfig(next);
    setSaving(true);
    saveConfig(next).then(() => { if (message) setToast(message); }).catch(err => setToast(`Save failed: ${err instanceof Error ? err.message : 'storage unavailable'}`)).finally(() => setSaving(false));
  }, [config]);
  const updateProfile = (id: string, updater: (profile: Profile) => Profile, note?: string) => mutate(c => ({ ...c, profiles: c.profiles.map(p => p.id === id ? updater(p) : p) }), note);
  const setMaster = (value: boolean) => mutate(c => ({ ...c, masterEnabled: value }), value ? 'Header changes enabled' : 'Header changes paused');
  const toggleProfile = (p: Profile) => mutate(c => {
    const enabled = !p.enabled;
    const active = new Set(enabled ? [...c.activeProfileIds, p.id] : c.activeProfileIds.filter(id => id !== p.id));
    return { ...c, profiles: c.profiles.map(item => item.id === p.id ? { ...item, enabled } : item), activeProfileIds: c.profiles.filter(item => active.has(item.id)).map(item => item.id) };
  }, p.enabled ? 'Profile paused' : 'Profile enabled');
  const chooseActive = (id: string) => setSelectedProfileId(id);
  const openOptionsPage = () => {
    if (window.chrome?.runtime?.openOptionsPage) {
      void window.chrome.runtime.openOptionsPage().catch(() => setLocation('/options'));
    } else {
      setLocation('/options');
    }
  };
  const openModal = (next: ModalState) => setModal(next);

  if (loadError) return <div className="app-shell"><div className="content"><div className="error-panel" role="alert">{loadError}<p><button className="btn btn-small" onClick={() => { setLoadError(''); loadConfig().then(setConfig).catch(e => setLoadError(String(e))); }} data-testid="button-retry-load"><RotateCcw size={13}/> Retry</button></p></div></div></div>;
  if (!config) return <div className={`app-shell ${!isOptions ? 'popup-shell' : ''}`} aria-label="Loading HeaderForge"><div className="topbar"><Brand/></div><div className="content"><div className="card" style={{padding:20}}><div className="skeleton-line"/><div className="skeleton-line"/><div className="skeleton-line"/></div></div></div>;

  const rootClass = `${isOptions ? 'app-shell' : 'app-shell popup-shell'}`;
  return <div className={rootClass}>
    {isOptions ? <OptionsHeader saving={saving} /> : <div className="topbar"><Brand compact/><div className="top-actions"><button className="icon-button" onClick={openOptionsPage} aria-label="Open options" title="Open full dashboard" data-testid="link-options"><Settings2 size={16}/></button></div></div>}
    {isOptions ? <div className="main-layout"><aside className="sidebar"><div className="side-label">Workspace</div><a href="#profiles" className="nav-link active" data-testid="nav-profiles"><Layers3 size={15}/>Profiles & rules</a><a href="#backup" className="nav-link" data-testid="nav-backup"><FileJson size={15}/>Backup & sharing</a><a href="#settings" className="nav-link" data-testid="nav-settings"><Settings2 size={15}/>Settings</a><div className="side-note"><LockKeyhole size={14} style={{verticalAlign:'-3px',marginRight:5}}/> Stored on this device. HeaderForge never sends your rules anywhere.</div></aside>
      <main className="content"><div className="page-heading"><div><div className="eyebrow">HeaderForge / Control room</div><h1>Profiles & rules</h1><p>Precise request and response edits, applied locally in your browser.</p></div><div className="heading-actions"><button className="btn" onClick={() => exportConfig(config)} data-testid="button-export-top"><Download size={14}/>Export JSON</button><button className="btn btn-primary" onClick={() => openModal({kind:'profile'})} data-testid="button-add-profile"><Plus size={15}/>New profile</button></div></div>
       <Dashboard config={config} activeProfile={activeProfile} openModal={openModal} mutate={mutate} updateProfile={updateProfile} toggleProfile={toggleProfile} chooseActive={chooseActive} bulkSelected={bulkSelected} setBulkSelected={setBulkSelected} testUrl={testUrl} setTestUrl={setTestUrl} testProfileId={testProfileId} setTestProfileId={setTestProfileId} restoreMode={restoreMode} setRestoreMode={setRestoreMode} fileRef={fileRef} importText={importText} setImportText={setImportText} toast={setToast}/>
       </main></div> : <Popup config={config} profile={activeProfile} popupTab={popupTab} setPopupTab={setPopupTab} setMaster={setMaster} toggleProfile={toggleProfile} chooseActive={chooseActive} openModal={openModal} mutate={mutate} openOptionsPage={openOptionsPage}/>}
    {modal && <EditorModal modal={modal} close={() => setModal(null)} config={config} mutate={mutate} updateProfile={updateProfile} onProfileCreated={setSelectedProfileId}/>}
    {toast && <div className="toast" role="status" data-testid="status-toast">{toast}</div>}
    <Switch><Route path="/"><span/></Route><Route path="/index.html"><span/></Route><Route path="/options"><span/></Route><Route path="/options.html"><span/></Route><Route><div className="not-found">This HeaderForge page does not exist. <Link href="/" data-testid="link-home">Return to popup</Link></div></Route></Switch>
  </div>;
}

function Brand({compact=false}:{compact?:boolean}) { return <Link href="/" className={`brand ${compact?'popup-brand':''}`} data-testid="link-brand"><span className="brand-mark"><Braces size={16}/></span><span>headerforge</span></Link>; }
function OptionsHeader({saving}:{saving:boolean}) { return <header className="topbar"><Brand/><div className="top-actions"><span className="status-pill" data-testid="status-storage"><span className="status-dot"/>{saving?'Saving':'Local only'}</span><Link href="/" className="btn btn-small" data-testid="link-popup"><ExternalLink size={13}/>Popup</Link></div></header>; }
function Popup({config,profile,popupTab,setPopupTab,setMaster,toggleProfile,chooseActive,openModal,mutate,openOptionsPage}:{config:AppStorage;profile?:Profile;popupTab:'request'|'response'|'filters';setPopupTab:(t:'request'|'response'|'filters')=>void;setMaster:(v:boolean)=>void;toggleProfile:(p:Profile)=>void;chooseActive:(id:string)=>void;openModal:(m:ModalState)=>void;mutate:(fn:(c:AppStorage)=>AppStorage,note?:string)=>void;openOptionsPage:()=>void}) {
  const setScope = (scope:'global'|'tab') => mutate(c=>({...c,settings:{...c.settings,tabScopeDefault:scope}}),`Scope set to ${scope === 'tab'?'this tab':'all tabs'}`);
  return <div className="popup-content">
    <section className="hero-status"><div><h2>Request control</h2><p>{config.masterEnabled?'Header rules are active on matching traffic':'All header changes are paused'}</p></div><input type="checkbox" className="toggle big-toggle" checked={config.masterEnabled} onChange={e=>setMaster(e.target.checked)} aria-label="Enable HeaderForge globally" data-testid="toggle-master"/></section>
     <div className="profile-row"><span className="profile-color" style={{'--tag-color':profile?COLOR_MAP[profile.colorTag]||COLOR_MAP.teal:COLOR_MAP.teal} as CSSProperties}/><select className="select inline-select" aria-label="Select profile to edit" value={profile?.id||''} onChange={e=>chooseActive(e.target.value)} data-testid="select-active-profile">{config.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><span className="profile-name" style={{flex:'none',fontSize:10,color:'var(--muted-ink)'}}>{profile?.enabled?'ON':'OFF'}</span><input className="toggle" type="checkbox" checked={!!profile?.enabled} disabled={!profile} onChange={()=>profile&&toggleProfile(profile)} aria-label="Toggle selected profile" data-testid="toggle-profile"/></div>
    <div className="switch-row" style={{padding:'4px 1px 12px'}}><div className="switch-copy">Apply to <small>Rule matching scope</small></div><div className="tabs"><button className={`tab ${config.settings.tabScopeDefault==='tab'?'active':''}`} onClick={()=>setScope('tab')} data-testid="button-scope-tab">This tab</button><button className={`tab ${config.settings.tabScopeDefault==='global'?'active':''}`} onClick={()=>setScope('global')} data-testid="button-scope-global">All tabs</button></div></div>
    <div className="tabs" style={{marginBottom:5}} role="tablist" aria-label="Rule categories">{(['request','response','filters'] as const).map(t=><button key={t} className={`tab ${popupTab===t?'active':''}`} onClick={()=>setPopupTab(t)} role="tab" aria-selected={popupTab===t} data-testid={`tab-${t}`}>{t==='filters'?'URL filters':`${t[0].toUpperCase()}${t.slice(1)}`}</button>)}</div>
    <div className="card" style={{padding:'0 12px'}}>
      {!profile ? <div className="empty"><strong>No profiles yet</strong>Create a profile in the options dashboard.</div> : popupTab==='filters' ? <FilterRows profile={profile} openModal={openModal} updateProfile={(fn)=>mutate(c=>({...c,profiles:c.profiles.map(p=>p.id===profile.id?fn(p):p)}))}/> : <HeaderRows profile={profile} type={popupTab} openModal={openModal} updateProfile={(fn)=>mutate(c=>({...c,profiles:c.profiles.map(p=>p.id===profile.id?fn(p):p)}))}/>}
    </div>
     <div className="popup-footer"><button className="btn btn-small" onClick={()=>exportConfig(config)} data-testid="button-quick-export"><Download size={13}/>Export</button><button className="btn btn-small" onClick={()=>document.getElementById('quick-import')?.click()} data-testid="button-quick-import"><Upload size={13}/>Import</button><input id="quick-import" type="file" accept="application/json,.json" hidden onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=parseConfigurationImport(JSON.parse(await file.text()));const next=applyImportedConfig(config,parsed.config,'merge');mutate(()=>next,parsed.format==='modheader'?'ModHeader profiles imported':'Profiles imported');const target=next.profiles.at(-1)?.id;if(target)chooseActive(target);}catch(err){window.alert(err instanceof Error?err.message:'Invalid JSON');}e.target.value='';}}/><button className="btn btn-small btn-primary" onClick={openOptionsPage} data-testid="button-open-dashboard"><Settings2 size={13}/>Dashboard</button></div>
  </div>;
}

function HeaderRows({profile,type,openModal,updateProfile}:{profile:Profile;type:'request'|'response';openModal:(m:ModalState)=>void;updateProfile:(fn:(p:Profile)=>Profile)=>void}) {
  const rows=profile.headers.filter(h=>h.type===type);
  return <>{rows.length?rows.map(h=><div className="rule-row" key={h.id}><input type="checkbox" className="toggle" checked={h.enabled} onChange={()=>updateProfile(p=>({...p,headers:p.headers.map(x=>x.id===h.id?{...x,enabled:!x.enabled}:x)}))} aria-label={`Toggle ${h.name}`} data-testid={`toggle-header-${h.id}`}/><button className="rule-copy" onClick={()=>openModal({kind:'header',item:h})} data-testid={`edit-header-${h.id}`}><div className="rule-name">{h.name}</div><div className="rule-value">{h.operation==='remove'?'Remove header':h.value}</div><div className="rule-meta"><span className={`tag ${h.type}`}>{h.operation}</span>{h.resourceTypes.length?`${h.resourceTypes.length} types`:'all types'}</div></button><button className="icon-button" aria-label={`Remove ${h.name}`} onClick={()=>updateProfile(p=>({...p,headers:p.headers.filter(x=>x.id!==h.id)}))} data-testid={`delete-header-${h.id}`}><Trash2 size={14}/></button></div>):<div className="empty"><strong>No {type} headers</strong>Add a rule to start shaping traffic.</div>}<button className="btn btn-small" style={{margin:'9px 0 12px'}} onClick={()=>openModal({kind:'header'})} data-testid={`button-add-${type}-header`}><Plus size={13}/>Add {type} header</button></>;
}
function FilterRows({profile,openModal,updateProfile}:{profile:Profile;openModal:(m:ModalState)=>void;updateProfile:(fn:(p:Profile)=>Profile)=>void}) {
  return <>{profile.filters.length?profile.filters.map(f=><div className="rule-row" key={f.id}><Globe2 size={15} color="var(--teal)"/><button className="rule-copy" onClick={()=>openModal({kind:'filter',item:f})} data-testid={`edit-filter-${f.id}`}><div className="rule-name">{f.urlPattern}</div><div className="rule-meta">{f.isRegex?'Regular expression':'URL pattern'} · {f.resourceTypes.length?`${f.resourceTypes.length} types`:'all types'}</div></button><button className="icon-button" onClick={()=>updateProfile(p=>({...p,filters:p.filters.filter(x=>x.id!==f.id)}))} aria-label="Remove filter" data-testid={`delete-filter-${f.id}`}><Trash2 size={14}/></button></div>):<div className="empty"><strong>No URL filters</strong>Rules match every URL until you add a filter.</div>}<button className="btn btn-small" style={{margin:'9px 0 12px'}} onClick={()=>openModal({kind:'filter'})} data-testid="button-add-filter"><Plus size={13}/>Add URL filter</button></>;
}

function Dashboard(props: {config:AppStorage;activeProfile?:Profile;openModal:(m:ModalState)=>void;mutate:(fn:(c:AppStorage)=>AppStorage,note?:string)=>void;updateProfile:(id:string,fn:(p:Profile)=>Profile,note?:string)=>void;toggleProfile:(p:Profile)=>void;chooseActive:(id:string)=>void;bulkSelected:string[];setBulkSelected:(ids:string[])=>void;testUrl:string;setTestUrl:(s:string)=>void;testProfileId:string;setTestProfileId:(s:string)=>void;restoreMode:'merge'|'replace';setRestoreMode:(m:'merge'|'replace')=>void;fileRef:RefObject<HTMLInputElement|null>;importText:string;setImportText:(s:string)=>void;toast:(s:string)=>void}) {
 const {config,activeProfile,openModal,mutate,updateProfile,toggleProfile,chooseActive,bulkSelected,setBulkSelected,testUrl,setTestUrl,testProfileId,setTestProfileId,restoreMode,setRestoreMode,fileRef,importText,setImportText,toast}=props;
 const testProfile=config.profiles.find(p=>p.id===testProfileId)||activeProfile;
 const matching=testProfile?.filters.filter(f=>matchFilter(f,testUrl))??[];
  const moveProfile=(index:number,direction:-1|1)=>mutate(c=>{const ps=[...c.profiles];const target=index+direction;if(target<0||target>=ps.length)return c;[ps[index],ps[target]]=[ps[target],ps[index]];const active=new Set(c.activeProfileIds);return {...c,profiles:ps,activeProfileIds:ps.filter(p=>active.has(p.id)).map(p=>p.id)};},'Profile order updated');
  const reorderProfiles=(sourceId:string,targetId:string)=>mutate(c=>{const ps=[...c.profiles];const from=ps.findIndex(p=>p.id===sourceId),to=ps.findIndex(p=>p.id===targetId);if(from<0||to<0||from===to)return c;const [item]=ps.splice(from,1);ps.splice(to,0,item);const active=new Set(c.activeProfileIds);return {...c,profiles:ps,activeProfileIds:ps.filter(p=>active.has(p.id)).map(p=>p.id)};},'Profile priority updated');
  const duplicateProfile=(profile:Profile)=>{const copy:Profile={...profile,id:createId('profile'),name:`${profile.name} copy`,enabled:false,headers:profile.headers.map(h=>({...h,id:createId('header')})),filters:profile.filters.map(f=>({...f,id:createId('filter')}))};mutate(c=>({...c,profiles:[...c.profiles,copy]}),'Profile duplicated');chooseActive(copy.id);};
  const reorderHeaders=(profile:Profile,sourceId:string,targetId:string)=>updateProfile(profile.id,p=>{const headers=[...p.headers];const from=headers.findIndex(h=>h.id===sourceId),to=headers.findIndex(h=>h.id===targetId);if(from<0||to<0||from===to)return p;const [item]=headers.splice(from,1);headers.splice(to,0,item);return {...p,headers};},'Rule priority updated');
 const bulkAction=(action:'on'|'off'|'delete')=>{if(!activeProfile)return;updateProfile(activeProfile.id,p=>({...p,headers:action==='delete'?p.headers.filter(h=>!bulkSelected.includes(h.id)):p.headers.map(h=>bulkSelected.includes(h.id)?{...h,enabled:action==='on'}:h)}),action==='delete'?'Rules deleted':'Rules updated');setBulkSelected([]);};
  const fileImport=async(file?:File)=>{if(!file)return;try{const parsed=parseConfigurationImport(JSON.parse(await file.text()));importConfiguration(parsed.config,restoreMode,parsed.format);}catch(err){toast(err instanceof Error?err.message:'Invalid configuration file');}};
  const importConfiguration=(incoming:AppStorage,mode:'merge'|'replace',format:'headerforge'|'modheader'='headerforge')=>{const next=applyImportedConfig(config,incoming,mode);mutate(()=>next,format==='modheader'?'ModHeader profiles imported':mode==='replace'?'Backup restored':'Profiles merged');const target=mode==='replace'?next.profiles[0]?.id:next.profiles.at(-1)?.id;if(target)chooseActive(target);};
  const importModHeader=()=>{try {const parsed=parseConfigurationImport(JSON.parse(importText));const next=applyImportedConfig(config,parsed.config,'merge');mutate(()=>next,parsed.format==='modheader'?'ModHeader profiles imported':'Profiles imported');const target=next.profiles.at(-1)?.id;if(target)chooseActive(target);setImportText('');}catch(err){toast(err instanceof Error?err.message:'Could not import rules');}};
 return <div className="stack">
   <section className="hero-status"><div><h2>{config.masterEnabled?'Header engine live':'Header engine paused'}</h2><p>{config.profiles.length} profiles · {config.profiles.reduce((n,p)=>n+p.headers.filter(h=>h.enabled).length,0)} enabled header rules configured</p></div><label className="switch-row"><span className="switch-copy">{config.masterEnabled?'Enabled':'Paused'}</span><input type="checkbox" className="toggle big-toggle" checked={config.masterEnabled} onChange={e=>mutate(c=>({...c,masterEnabled:e.target.checked}))} aria-label="Master enable" data-testid="toggle-master-dashboard"/></label></section>
   <div className="section-grid"><div className="stack">
      <section className="card" id="profiles"><div className="card-head"><div><div className="card-title">Profiles</div><div className="rule-meta" style={{marginTop:4}}>Enable more than one profile to layer rules; order sets priority</div></div><button className="btn btn-small btn-primary" onClick={()=>openModal({kind:'profile'})} data-testid="button-create-profile"><Plus size={13}/>Create</button></div><div className="card-body"><div className="profile-list">{config.profiles.map((p,i)=><div className="profile-list-row" key={p.id} data-testid={`profile-row-${p.id}`} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',p.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorderProfiles(e.dataTransfer.getData('text/plain'),p.id);}}><GripVertical className="drag-handle" size={15}/><span className="profile-color" style={{'--tag-color':COLOR_MAP[p.colorTag]||COLOR_MAP.teal,height:23,width:7} as CSSProperties}/><button className="profile-summary" style={{border:0,padding:0,textAlign:'left',background:'transparent'}} onClick={()=>chooseActive(p.id)} data-testid={`select-profile-${p.id}`}><strong>{p.name} {activeProfile?.id===p.id?'· selected':''}</strong><small>{p.headers.length} headers / {p.filters.length} filters</small></button><span className="profile-count">{p.enabled?'ACTIVE':'OFF'}</span><div style={{display:'flex',alignItems:'center'}}><button className="icon-button" aria-label={`Move ${p.name} up`} disabled={i===0} onClick={()=>moveProfile(i,-1)} data-testid={`move-profile-up-${p.id}`}><ArrowUp size={13}/></button><button className="icon-button" aria-label={`Move ${p.name} down`} disabled={i===config.profiles.length-1} onClick={()=>moveProfile(i,1)} data-testid={`move-profile-down-${p.id}`}><ArrowDown size={13}/></button><button className="icon-button" aria-label={`Edit ${p.name}`} onClick={()=>openModal({kind:'profile',item:p})} data-testid={`edit-profile-${p.id}`}><Settings2 size={14}/></button><button className="icon-button" aria-label={`Duplicate ${p.name}`} onClick={()=>duplicateProfile(p)} data-testid={`duplicate-profile-${p.id}`}><Copy size={14}/></button><button className="icon-button" aria-label={`Delete ${p.name}`} onClick={()=>{if(window.confirm(`Delete profile “${p.name}” and its rules?`))mutate(c=>({...c,profiles:c.profiles.filter(x=>x.id!==p.id),activeProfileIds:c.activeProfileIds.filter(id=>id!==p.id)}),'Profile deleted');}} data-testid={`delete-profile-${p.id}`}><Trash2 size={14}/></button><input className="toggle" type="checkbox" checked={p.enabled} onChange={()=>toggleProfile(p)} aria-label={`Toggle ${p.name}`} data-testid={`toggle-profile-${p.id}`}/></div></div>)}
       {!config.profiles.length&&<div className="empty"><strong>Your first profile is a clean slate</strong>Group header rules by environment, project, or task.<button className="btn btn-primary btn-small" onClick={()=>openModal({kind:'profile'})} data-testid="button-create-first-profile"><Plus size={13}/>Create a profile</button></div>}</div></div></section>
      {activeProfile&&<section className="card"><div className="card-head"><div><div className="card-title">{activeProfile.name} · Header rules</div><div className="rule-meta" style={{marginTop:4}}>Enabled rules are compiled into browser request controls.</div></div><div style={{display:'flex',gap:6}}><button className="btn btn-small" onClick={()=>exportProfile(config,activeProfile)} data-testid="button-export-profile"><Download size={13}/>Export profile</button><button className="btn btn-small" onClick={()=>copyProfileJson(config,activeProfile,toast)} data-testid="button-copy-profile"><Copy size={13}/>Copy profile</button><button className="btn btn-small btn-primary" onClick={()=>openModal({kind:'header'})} data-testid="button-add-rule"><Plus size={13}/>Add rule</button></div></div><div className="card-body" style={{paddingTop:8}}>{activeProfile.headers.length>0&&<div className="switch-row" style={{padding:'0 0 9px'}}><label className="check-label"><input type="checkbox" checked={bulkSelected.length>0&&bulkSelected.length===activeProfile.headers.length} onChange={e=>setBulkSelected(e.target.checked?activeProfile.headers.map(h=>h.id):[])} data-testid="checkbox-select-all-rules"/>Select all rules</label>{bulkSelected.length>0&&<div style={{display:'flex',gap:5}}><button className="btn btn-small" onClick={()=>bulkAction('on')} data-testid="button-bulk-enable">Enable</button><button className="btn btn-small" onClick={()=>bulkAction('off')} data-testid="button-bulk-disable">Disable</button><button className="btn btn-small btn-danger" onClick={()=>bulkAction('delete')} data-testid="button-bulk-delete"><Trash2 size={12}/>Delete</button></div>}</div>}
        {activeProfile.headers.length?activeProfile.headers.map((h,index)=><div className="rule-row rule-order-row" key={h.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',h.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorderHeaders(activeProfile,e.dataTransfer.getData('text/plain'),h.id);}}><GripVertical size={14} className="drag-handle"/><input type="checkbox" checked={bulkSelected.includes(h.id)} onChange={e=>setBulkSelected(e.target.checked?[...bulkSelected,h.id]:bulkSelected.filter(id=>id!==h.id))} aria-label={`Select ${h.name}`} data-testid={`select-rule-${h.id}`}/><div><button className="rule-name" style={{border:0,padding:0,background:'none',textAlign:'left'}} onClick={()=>openModal({kind:'header',item:h})} data-testid={`edit-rule-${h.id}`}>{h.name}</button><div className="rule-value">{h.operation==='remove'?'—':h.value||'(empty value)'}</div><div className="rule-meta"><span className={`tag ${h.type}`}>{h.type}</span><span className="tag">{h.operation}</span><span>{h.resourceTypes.length?`${h.resourceTypes.length} resource types`:'all resource types'}</span></div></div><div style={{display:'flex',alignItems:'center',gap:8}}><button className="icon-button" aria-label={`Move ${h.name} up`} disabled={index===0} onClick={()=>reorderHeaders(activeProfile,h.id,activeProfile.headers[index-1]?.id??h.id)} data-testid={`move-rule-up-${h.id}`}><ArrowUp size={13}/></button><button className="icon-button" aria-label={`Move ${h.name} down`} disabled={index===activeProfile.headers.length-1} onClick={()=>reorderHeaders(activeProfile,h.id,activeProfile.headers[index+1]?.id??h.id)} data-testid={`move-rule-down-${h.id}`}><ArrowDown size={13}/></button><input className="toggle" type="checkbox" checked={h.enabled} onChange={()=>updateProfile(activeProfile.id,p=>({...p,headers:p.headers.map(x=>x.id===h.id?{...x,enabled:!x.enabled}:x)}))} aria-label={`Enable ${h.name}`} data-testid={`toggle-rule-${h.id}`}/><button className="icon-button" aria-label={`Delete ${h.name}`} onClick={()=>updateProfile(activeProfile.id,p=>({...p,headers:p.headers.filter(x=>x.id!==h.id)}),'Rule deleted')} data-testid={`delete-rule-${h.id}`}><Trash2 size={14}/></button></div></div>):<div className="empty"><strong>No header rules in this profile</strong>Add a request or response rule to get started.</div>}
     </div></section>}
     {activeProfile&&<section className="card"><div className="card-head"><div className="card-title">URL filters</div><button className="btn btn-small" onClick={()=>openModal({kind:'filter'})} data-testid="button-create-filter"><Plus size={13}/>Add filter</button></div><div className="card-body">{activeProfile.filters.length?activeProfile.filters.map(f=><div className="rule-row" key={f.id}><Globe2 size={15} color="var(--teal)"/><button className="rule-copy" onClick={()=>openModal({kind:'filter',item:f})} data-testid={`edit-url-filter-${f.id}`}><div className="rule-name">{f.urlPattern}</div><div className="rule-meta">{f.isRegex?'Regex':'Wildcard pattern'} · {f.resourceTypes.length?`${f.resourceTypes.length} resource types`:'all types'}</div></button><button className="icon-button" onClick={()=>updateProfile(activeProfile.id,p=>({...p,filters:p.filters.filter(x=>x.id!==f.id)}),'Filter removed')} aria-label="Delete URL filter" data-testid={`remove-filter-${f.id}`}><Trash2 size={14}/></button></div>):<div className="empty"><strong>No URL filters</strong>Without filters, enabled rules can match any URL.</div>}</div></section>}
      <section className="card" id="url-tester"><div className="card-head"><div className="card-title"><Globe2 size={15} style={{verticalAlign:'-3px',marginRight:7}}/>URL tester</div><span className="eyebrow">Local evaluation</span></div><div className="card-body"><div className="form-row"><div className="field"><label htmlFor="url-test-profile">Profile</label><select id="url-test-profile" className="select" value={testProfile?.id||''} onChange={e=>setTestProfileId(e.target.value)} data-testid="select-test-profile">{config.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label htmlFor="url-test-input">URL to test</label><input id="url-test-input" className="input mono" placeholder="https://api.example.dev/v1" value={testUrl} onChange={e=>setTestUrl(e.target.value)} data-testid="input-test-url"/></div></div><div className="tester-result" data-testid="result-url-test">{!testUrl?'Enter a URL to evaluate profile filters.':matching.length?`${matching.length} matching filter${matching.length===1?'':'s'} · ${matching.map(f=>f.urlPattern).join(', ')}`:testProfile?.filters.length?'No filters match this URL.':'No filters configured — all URLs pass.'}</div><button className="btn btn-small" style={{marginTop:10}} disabled={!testUrl||!testProfile} onClick={()=>copyCurlCommand(config,testProfile,testUrl,toast)} data-testid="button-copy-curl"><Copy size={13}/>Copy as cURL</button><div className="rule-meta" style={{marginTop:7}}>Copies matching request headers only; response-header rules are browser-only.</div></div></section>
   </div><div className="stack">
    <section className="card" id="backup"><div className="card-head"><div className="card-title"><FileJson size={15} style={{verticalAlign:'-3px',marginRight:7}}/>Backup & sharing</div></div><div className="card-body"><p style={{fontSize:11,color:'var(--muted-ink)',lineHeight:1.55,margin:'0 0 14px'}}>Configuration files contain your header values. Keep exports private if they include credentials.</p><div className="stack" style={{gap:8}}><button className="btn" onClick={()=>exportConfig(config)} data-testid="button-export-config"><Download size={14}/>Download JSON backup</button><button className="btn" onClick={()=>fileRef.current?.click()} data-testid="button-restore-config"><Upload size={14}/>Restore JSON backup</button><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e=>{void fileImport(e.target.files?.[0]);e.target.value='';}}/><div className="field" style={{margin:'8px 0 0'}}><label>Restore behavior</label><select className="select" value={restoreMode} onChange={e=>setRestoreMode(e.target.value as 'merge'|'replace')} data-testid="select-restore-mode"><option value="merge">Merge profiles</option><option value="replace">Replace all configuration</option></select></div><button className="btn" onClick={()=>{navigator.clipboard?.writeText(JSON.stringify(config,null,2)).then(()=>toast('Configuration copied to clipboard')).catch(()=>toast('Clipboard unavailable'));}} data-testid="button-copy-config"><Copy size={14}/>Copy configuration</button></div><div className="notice">Backup and clipboard data stays on this device unless you share it.</div></div></section>
     <section className="card"><div className="card-head"><div className="card-title">ModHeader import</div><button className="icon-button" title="Import a JSON export of profiles, filters, and header rules"><CircleHelp size={15}/></button></div><div className="card-body"><div className="field"><label htmlFor="modheader-json">Paste exported configuration JSON</label><textarea id="modheader-json" className="textarea" placeholder={'[{ "title": "Staging", "headers": [{ "name": "X-Debug", "value": "true" }] }]'} value={importText} onChange={e=>setImportText(e.target.value)} data-testid="textarea-modheader-json"/></div><button className="btn" onClick={importModHeader} data-testid="button-import-modheader"><Upload size={13}/>Import profiles</button></div></section>
     <section className="card"><div className="card-head"><div className="card-title"><Zap size={14} style={{verticalAlign:'-3px',marginRight:6}}/>Dynamic token helper</div></div><div className="card-body"><p style={{margin:'0 0 10px',fontSize:11,color:'var(--muted-ink)',lineHeight:1.5}}>Tokens are resolved by the extension worker. The timestamp and ISO date refresh once a minute; random values are generated when rules are compiled.</p>{['{{$timestamp}}','{{$isoDate}}','{{$uuid}}','{{$randomInt(1,10)}}'].map(token=><div className="rule-row" key={token}><code className="mono" style={{fontSize:11,flex:1}}>{token}</code><button className="icon-button" aria-label={`Copy ${token}`} onClick={()=>navigator.clipboard?.writeText(token).then(()=>toast(`${token} copied`)).catch(()=>toast('Clipboard unavailable'))} data-testid={`button-copy-token-${token.replace(/[{}$()]/g,'').replaceAll(',','-').replaceAll(' ','')}`}><Copy size={13}/></button></div>)}</div></section>
    <section className="card" id="settings"><div className="card-head"><div className="card-title"><SlidersHorizontal size={15} style={{verticalAlign:'-3px',marginRight:7}}/>Settings</div></div><div className="card-body stack" style={{gap:14}}><div className="field" style={{margin:0}}><label htmlFor="theme-setting">Appearance</label><select className="select" id="theme-setting" value={config.settings.theme} onChange={e=>mutate(c=>({...c,settings:{...c.settings,theme:e.target.value as AppStorage['settings']['theme']}}))} data-testid="select-theme"><option value="system">Follow system</option><option value="light">Light</option><option value="dark">Dark</option></select></div><div className="switch-row"><div className="switch-copy">Badge count<small>Show enabled rule count on extension icon</small></div><input className="toggle" type="checkbox" checked={config.settings.showBadgeCount} onChange={e=>mutate(c=>({...c,settings:{...c.settings,showBadgeCount:e.target.checked}}))} aria-label="Show badge count" data-testid="toggle-badge-count"/></div><div className="field" style={{margin:0}}><label htmlFor="default-scope">Default tab scope</label><select className="select" id="default-scope" value={config.settings.tabScopeDefault} onChange={e=>mutate(c=>({...c,settings:{...c.settings,tabScopeDefault:e.target.value as 'global'|'tab'}}))} data-testid="select-default-scope"><option value="global">All tabs</option><option value="tab">Current tab</option></select></div></div></section>
   </div></div>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',paddingTop:4,color:'var(--muted-ink)',fontSize:10}}><span><ShieldCheck size={12} style={{verticalAlign:'-2px',marginRight:5}}/>Local-first · no account · no server</span><button className="btn btn-small btn-quiet btn-danger" onClick={()=>{if(window.confirm('Delete every profile and restore the defaults?')){loadConfig().then(c=>mutate(()=>({...c,profiles:[],activeProfileIds:[],masterEnabled:false}),'Profiles cleared'));}}} data-testid="button-clear-profiles"><Trash2 size={12}/>Clear profiles</button></div>
 </div>;
}

 function matchFilter(filter:FilterCondition,url:string) { return !!url && matchesUrlPattern(filter.urlPattern,url,filter.isRegex); }
 function downloadJson(config:AppStorage,fileName:string) { const blob=new Blob([JSON.stringify(config,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=fileName;link.click();window.setTimeout(()=>URL.revokeObjectURL(link.href),1000); }
 function exportConfig(config:AppStorage) { downloadJson(config,`headerforge-${new Date().toISOString().slice(0,10)}.json`); }
 function exportProfile(config:AppStorage,profile:Profile) { const backup={...config,profiles:[profile],activeProfileIds:config.activeProfileIds.includes(profile.id)?[profile.id]:[]};downloadJson(backup,`headerforge-${profile.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'profile'}.json`); }
 function copyProfileJson(config:AppStorage,profile:Profile,toast:(message:string)=>void) { const backup={...config,profiles:[profile],activeProfileIds:config.activeProfileIds.includes(profile.id)?[profile.id]:[]};if(!navigator.clipboard?.writeText){toast('Clipboard unavailable');return;}void navigator.clipboard.writeText(JSON.stringify(backup,null,2)).then(()=>toast('Profile configuration copied')).catch(()=>toast('Clipboard unavailable')); }
 function copyCurlCommand(config:AppStorage,profile:Profile|undefined,url:string,toast:(message:string)=>void) {
   if(!profile||!url)return;
   let parsedUrl:URL;try{parsedUrl=new URL(url);if(!['http:','https:'].includes(parsedUrl.protocol))throw new Error();}catch{toast('Enter a valid HTTP or HTTPS URL first');return;}
   const profileIsActive=config.masterEnabled&&profile.enabled&&config.activeProfileIds.includes(profile.id);
   const filtersMatch=profile.filters.length===0||profile.filters.some(f=>matchFilter(f,url)&&(!f.resourceTypes.length||f.resourceTypes.includes('xmlhttprequest')));
   const headers=profileIsActive&&filtersMatch?profile.headers.filter(h=>h.enabled&&h.type==='request'&&(!h.resourceTypes.length||h.resourceTypes.includes('xmlhttprequest'))):[];
   const quote=(value:string)=>`'${value.replaceAll("'", "'\\''")}'`;
   const lines=[`curl --request GET ${quote(parsedUrl.href)}`,...headers.map(h=>`  --header ${quote(`${h.name}: ${h.operation==='remove'?'':h.value}`)}`)];
   if(!navigator.clipboard?.writeText){toast('Clipboard unavailable');return;}
   const continuation=` ${String.fromCharCode(92)}\n`;
   void navigator.clipboard.writeText(lines.join(continuation)).then(()=>toast(`${headers.length} request header${headers.length===1?'':'s'} copied as cURL`)).catch(()=>toast('Clipboard unavailable'));
 }

 function EditorModal({modal,close,config,mutate,updateProfile,onProfileCreated}:{modal:Exclude<ModalState,null>;close:()=>void;config:AppStorage;mutate:(fn:(c:AppStorage)=>AppStorage,note?:string)=>void;updateProfile:(id:string,fn:(p:Profile)=>Profile,note?:string)=>void;onProfileCreated:(id:string)=>void}) {
 const [profileId,setProfileId]=useState(modal.item&&'headers'in modal.item?config.profiles.find(p=>p.headers.some(h=>h.id===modal.item?.id))?.id:modal.item&&'filters'in modal.item?config.profiles.find(p=>p.filters.some(f=>f.id===modal.item?.id))?.id:config.activeProfileIds[0]||config.profiles[0]?.id||'');
 const editing=modal.item;const [name,setName]=useState(modal.kind==='profile'?modal.item?.name||'':modal.kind==='header'?modal.item?.name||'':'');const [value,setValue]=useState(modal.kind==='header'?modal.item?.value||'':'');const [type,setType]=useState<'request'|'response'>(modal.kind==='header'?modal.item?.type||'request':'request');const [operation,setOperation]=useState<'set'|'append'|'remove'>(modal.kind==='header'?modal.item?.operation||'set':'set');const [color,setColor]=useState(modal.kind==='profile'?modal.item?.colorTag||'teal':'teal');const [pattern,setPattern]=useState(modal.kind==='filter'?modal.item?.urlPattern||'':'');const [isRegex,setIsRegex]=useState(modal.kind==='filter'?modal.item?.isRegex||false:false);const [resources,setResources]=useState<ResourceType[]>(modal.item&&'resourceTypes'in modal.item?modal.item.resourceTypes:[]);
 const isProfile=modal.kind==='profile', isHeader=modal.kind==='header';const heading=isProfile?(editing?'Edit profile':'New profile'):isHeader?(editing?'Edit header rule':'New header rule'):(editing?'Edit URL filter':'New URL filter');
  const save=(e:FormEvent)=>{e.preventDefault();if(isProfile){const profile:Profile={id:modal.item?.id||createId('profile'),name:name.trim(),colorTag:color,enabled:modal.item?.enabled||false,headers:modal.item&&'headers'in modal.item?modal.item.headers:[],filters:modal.item&&'filters'in modal.item?modal.item.filters:[]};if(modal.item)mutate(c=>({...c,profiles:c.profiles.map(p=>p.id===profile.id?profile:p)}),'Profile saved');else{mutate(c=>({...c,profiles:[...c.profiles,profile]}),'Profile created');onProfileCreated(profile.id);}close();return;}
  if(!profileId){return;}if(isHeader){const rule:HeaderRule={id:modal.item?.id||createId('header'),enabled:modal.item&&'enabled'in modal.item?modal.item.enabled:true,type,operation,name:name.trim(),value:operation==='remove'?'':value,resourceTypes:resources};updateProfile(profileId,p=>({...p,headers:modal.item?p.headers.map(h=>h.id===rule.id?rule:h):[...p.headers,rule]}),modal.item?'Rule updated':'Rule added');}
  else {const filter:FilterCondition={id:modal.item?.id||createId('filter'),urlPattern:pattern.trim(),isRegex,resourceTypes:resources};updateProfile(profileId,p=>({...p,filters:modal.item?p.filters.map(f=>f.id===filter.id?filter:f):[...p.filters,filter]}),modal.item?'Filter updated':'Filter added');}close();};
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><form className="modal" onSubmit={save} aria-label={heading}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{heading}</h2><button type="button" className="icon-button" onClick={close} aria-label="Close editor" data-testid="button-close-modal"><X size={17}/></button></div>
 {isProfile?<><div className="field"><label htmlFor="profile-name">Profile name</label><input id="profile-name" className="input" value={name} onChange={e=>setName(e.target.value)} required autoFocus placeholder="e.g. Local development" data-testid="input-profile-name"/></div><div className="field"><label>Color marker</label><div className="color-swatches">{COLOR_TAGS.map(c=><button key={c} type="button" className={`swatch ${color===c?'selected':''}`} style={{background:COLOR_MAP[c]}} onClick={()=>setColor(c)} aria-label={`Choose ${c} color`} data-testid={`color-${c}`}/>)}</div></div></>:<>
  <div className="field"><label>Profile</label><select className="select" value={profileId} onChange={e=>setProfileId(e.target.value)} data-testid="select-editor-profile">{config.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{!config.profiles.length&&<div className="notice">Create a profile before adding rules.</div>}</div>
  {isHeader?<><div className="form-row"><div className="field"><label htmlFor="header-name">Header name</label><input id="header-name" className="input mono" value={name} onChange={e=>setName(e.target.value)} required placeholder="X-Request-ID" autoFocus data-testid="input-header-name"/></div><div className="field"><label htmlFor="header-type">Direction</label><select id="header-type" className="select" value={type} onChange={e=>setType(e.target.value as 'request'|'response')} data-testid="select-header-type"><option value="request">Request</option><option value="response">Response</option></select></div></div><div className="form-row"><div className="field"><label htmlFor="header-operation">Operation</label><select id="header-operation" className="select" value={operation} onChange={e=>setOperation(e.target.value as 'set'|'append'|'remove')} data-testid="select-header-operation"><option value="set">Set / replace</option><option value="append">Append</option><option value="remove">Remove</option></select></div><div className="field"><label htmlFor="header-value">Value</label><input id="header-value" className="input mono" value={value} onChange={e=>setValue(e.target.value)} disabled={operation==='remove'} placeholder="value" data-testid="input-header-value"/></div></div></>:<><div className="field"><label htmlFor="filter-pattern">URL pattern</label><input id="filter-pattern" className="input mono" value={pattern} onChange={e=>setPattern(e.target.value)} required autoFocus placeholder="https://api.example.dev/*" data-testid="input-filter-pattern"/></div><label className="check-label" style={{marginBottom:14}}><input type="checkbox" checked={isRegex} onChange={e=>setIsRegex(e.target.checked)} data-testid="checkbox-filter-regex"/>Treat as regular expression</label></>}
  <div className="field"><label>Resource types <span style={{textTransform:'none',letterSpacing:0}}>(none selected = all)</span></label><div className="checks">{RESOURCE_TYPES.map(rt=><label className="check-label" key={rt}><input type="checkbox" checked={resources.includes(rt)} onChange={e=>setResources(e.target.checked?[...resources,rt]:resources.filter(r=>r!==rt))} data-testid={`checkbox-resource-${rt}`}/>{TYPE_LABELS[rt]}</label>)}</div></div>
 </>}
 <div className="modal-actions"><button type="button" className="btn" onClick={close} data-testid="button-cancel-editor">Cancel</button><button className="btn btn-primary" type="submit" disabled={!isProfile&&!profileId} data-testid="button-save-editor"><Check size={14}/>{editing?'Save changes':isProfile?'Create profile':'Add rule'}</button></div>
 </form></div>;
}

export default App;
